name: pr_creation

on:
  workflow_dispatch:
    inputs:
      repository:
          description: 'Repository'
          required: true
          default: 'TestOrganizationJavierAnton/Test'
      branch:
        description: 'Branch'
        required: false
        default: 'main'
      mode:
        description: 'pat, test'
        required: false
        default: 'pat'

env:
  USER_REPO_PATH: ${{ github.run_id }}/user_repo
  PROXY_REPO_PATH: ${{ github.run_id }}/proxy_repo
  SECRETS_PATH: ${{ github.run_id }}/secrets
  GITHUB_TOKEN: ${{ secrets.SECRET_PAT }}
  TOKEN: ${{ inputs.token }}
  PROXY_INFRA_FOLDER: 'terraform_templates'
  REPOSITORY: ${{ inputs.repository }}
  BRANCH:  ${{ inputs.branch }}

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.SECRET_PAT }}
          commit-message: Update report
          committer: Javi <javiantonyuste97@gmail.com>
          author: Javi <javiantonyuste97@gmail.com>
          signoff: false
          branch: example-pr
          delete-branch: true
          title: '[Example] Updated dile'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            automated pr
          assignees: JavierAntonYuste
          reviewers: JavierAntonYuste
          #team-reviewers: |
          milestone: 1
          draft: false

        
  clean_up:
    needs: createPullRequest
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Clean-up workspace
        run: |
          rm -rf ${{ github.run_id }} || true
